apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgres-pvc 
  namespace: milestone2-kb
  labels:
    app: postgres 
spec:
  #storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi