apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: milestone2-kb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: postgres
